---
development:
  cloud_name: austinhansen
  api_key: '792295966462899'
  api_secret: mHdgl15na7QQ0lgq9sk3vb2eGeo
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: austinhansen
  api_key: '792295966462899'
  api_secret: mHdgl15na7QQ0lgq9sk3vb2eGeo
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: austinhansen
  api_key: '792295966462899'
  api_secret: mHdgl15na7QQ0lgq9sk3vb2eGeo
  enhance_image_tag: true
  static_image_support: false
